development:
  adapter: postgresql
  database:  beautyche_development
  pool: 5

test:
  adapter: postgresql
  database: beautyche_test
  pool: 5

production:
  adapter: postgresql
  database: beautyche_development
  pool: 5
